version: "3.8"

services:
  web:
    container_name: fastapi
    build: .
    volumes:
      - .:/app
    environment:
      database_url: ${database_url}
      redis_url: ${redis_url}
      jwt_secret: ${jwt_secret}
      jwt_algorithm: ${jwt_algorithm}
      access_token_expiry: ${access_token_expiry}
      refresh_token_expiry: ${refresh_token_expiry}
      mail_username: ${mail_username}
      mail_password: ${mail_password}
      mail_from: ${mail_from}
      mail_port: ${mail_port}
      mail_server: ${mail_server}
      mail_from_name: ${mail_from_name}
      domain: ${domain}

    ports:
      - "8000:8000"

    depends_on:
      - redis

    networks:
      - app-network

  pgadmin:
    container_name: pgadmin4

    image: dpage/pgadmin4

    restart: always

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    networks:
      - app-network

  redis:
    container_name: redis

    image: redis:latest

    ports:
      - "6379:6379"

    networks:
      - app-network

  celery:
    container_name: celery

    build: .

    command: celery -A src.utils.celery_tasks.c_app worker --loglevel=INFO

    volumes:
      - .:/app

    depends_on:
      - redis

    environment:
      redis_url: ${redis_url}

    networks:
      - app-network

volumes:
  db-data:

networks:
  app-network:
    driver: bridge
