"""Initial migration

Revision ID: 9a35a7097606
Revises: f2e2dae0bd9b
Create Date: 2024-11-02 12:03:32.067211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a35a7097606'
down_revision: Union[str, None] = 'f2e2dae0bd9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role', 'id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
